#ifndef __PKEYS_H__
#define __PKEYS_H__

typedef enum {
    PKEY_ESCAPE = 0x01,
    PKEY_1,
    PKEY_2,
    PKEY_3,
    PKEY_4,
    PKEY_5,
    PKEY_6,
    PKEY_7,
    PKEY_8,
    PKEY_9,
    PKEY_0,
    PKEY_HYPHEN,    // -
    PKEY_EQUALS,
    PKEY_BACKSPACE,
    PKEY_TAB,
    PKEY_Q,
    PKEY_W,
    PKEY_E,
    PKEY_R,
    PKEY_T,
    PKEY_Y,
    PKEY_U,
    PKEY_I,
    PKEY_O,
    PKEY_P,
    PKEY_LEFT_BRACKET,
    PKEY_RIGHT_BRACKET,
    PKEY_ENTER,
    PKEY_LEFT_CONTROL,
    PKEY_A,
    PKEY_S,
    PKEY_D,
    PKEY_F,
    PKEY_G,
    PKEY_H,
    PKEY_J,
    PKEY_K,
    PKEY_L,
    PKEY_SEMICOLON,
    PKEY_SINGLE_QUOTE,
    PKEY_BACK_TICK, // `
    PKEY_LEFT_SHIFT,
    PKEY_BACK_SLASH,
    PKEY_Z,
    PKEY_X,
    PKEY_C,
    PKEY_V,
    PKEY_B,
    PKEY_N,
    PKEY_M,
    PKEY_COMMA,     // ,
    PKEY_PERIOD,    // .
    PKEY_SLASH,
    PKEY_RIGHT_SHIFT,
    PKEY_KEYPAD_STAR,
    PKEY_LEFT_ALT,
    PKEY_SPACE,
    PKEY_CAPSLOCK,
    PKEY_F1,
    PKEY_F2,
    PKEY_F3,
    PKEY_F4,
    PKEY_F5,
    PKEY_F6,
    PKEY_F7,
    PKEY_F8,
    PKEY_F9,
    PKEY_F10,
    PKEY_NUMBERLOCK,
    PKEY_SCROLLLOCK,
    PKEY_KEYPAD_7,
    PKEY_KEYPAD_8,
    PKEY_KEYPAD_9,
    PKEY_KEYPAD_HYPHEN,
    PKEY_KEYPAD_4,
    PKEY_KEYPAD_5,
    PKEY_KEYPAD_6,
    PKEY_KEYPAD_PLUS,
    PKEY_KEYPAD_1,
    PKEY_KEYPAD_2,
    PKEY_KEYPAD_3,
    PKEY_KEYPAD_0,
    PKEY_KEYPAD_PERIOD,
    PKEY_F11 = 0x57,
    PKEY_F12
} PhysicalKey;

#endif
